name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        type: [Debug, RelWithDebInfo, MinSizeRel, Release]
        config:
          - os: ubuntu-latest
            compiler: clang
            sanitizer: ''
          - os: ubuntu-latest
            compiler: gcc
            sanitizer: ''
          - os: ubuntu-latest
            compiler: tcc
            sanitizer: ''
          - os: windows-latest
            compiler: default
            sanitizer: ''
          - os: windows-latest
            compiler: clang
            sanitizer: ''
          - os: macos-latest
            compiler: default
            sanitizer: ''
          - os: ubuntu-latest
            compiler: clang
            sanitizer: address
          - os: ubuntu-latest
            compiler: clang
            sanitizer: memory
          - os: ubuntu-latest
            compiler: clang
            sanitizer: undefined
          - os: macos-latest
            compiler: default
            sanitizer: address
          - os: macos-latest
            compiler: default
            sanitizer: undefined
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Setup dependencies (Ubuntu)
      if: startsWith(matrix.config.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get install -y gcc-10 g++-10 clang tcc

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake_args=(-DCMAKE_BUILD_TYPE=${{ matrix.type }})
        if [ -n "${{ matrix.config.sanitizer }}" ]; then
          cmake_args+=("-DJSON_USE_SANITIZER=${{ matrix.config.sanitizer }}")
        fi

        if [ "${{ matrix.config.compiler }}" = "gcc" ]; then
          cmake "$GITHUB_WORKSPACE/test" "${cmake_args[@]}" -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
        elif [ "${{ matrix.config.compiler }}" = "tcc" ]; then
          cmake "$GITHUB_WORKSPACE/test" "${cmake_args[@]}" -DCMAKE_C_COMPILER=tcc -DCMAKE_CXX_COMPILER=g++-10
        elif [ "${{ matrix.config.compiler }}" = "clang" ] && [ "${{ matrix.config.os }}" = "ubuntu-latest" ]; then
          cmake "$GITHUB_WORKSPACE/test" "${cmake_args[@]}" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
        elif [ "${{ matrix.config.compiler }}" = "clang" ] && [ "${{ matrix.config.os }}" = "windows-latest" ]; then
          cmake "$GITHUB_WORKSPACE/test" "${cmake_args[@]}" -T ClangCL
        else
          cmake "$GITHUB_WORKSPACE/test" "${cmake_args[@]}"
        fi

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest --build-config ${{ matrix.type }} --output-on-failure
